### ISSUE TITLE
下载MP3音频实际下载MP4文件

### ISSUE THREAD

**Issue by KalunJ** [JiJiDown/Tracker#1]
**描述错误**
点击下载mp3文件，实际下载为mp4视频，而且音频解析好像不太正常，原来是直接把音轨类型写在文件名的，现在是none

**软件信息**

 - 你使用的是什么系统: Windows10 22H2
 - 软件版本号: git.r268.c713a0b2
 - (可选) 下载问题请添加视频地址: https://www.bilibili.com/video/BV1oP411f7KG

**重现**
重现此行为的步骤:

1. 复制视频链接
2. 点击 解析
3. 点击下载  MP3音频文件
4. 实际下载为 MP4文件

**预期行为**
对您预期会发生什么的清晰简洁的描述。

**附加日志**
[日志txt](https://github.com/JiJiDown/Tracker/files/10948413/MP3.MP4.txt)
[下载MP3后的实际文件名称截图](https://user-images.githubusercontent.com/100948935/224482562-057f30fa-9871-4daa-b096-ab9c2883bdaa.png)
(https://pastebin.com/spxgFd6b)

日志获取方法请参阅 [唧唧 2.0 如何 Debug | 调试](http://client.jijidown.com/quick_start/how_to_debug/)

日志太长可以使用 pastebin 分享日志

```log

```

**Comment by xiahuaijia** [comment]
感谢反馈, 问题已确认

**Comment by xiahuaijia** [comment]
请更新到 `git.r270.c1660e47 (2023.03.18)`, 确认问题是否修复

**Comment by KalunJ** [comment]
问题：
mp3下载正常了，但是我无法下载视频文件
更新后就是正常解析，然后下载任何视频文件都报错，大概就是无法获取信息（没出国，光猫也重拨号IP了）


还有就是报错后前往任务列表取消任务，可能出现两种情况
1.任务数量不变，变成幽灵任务，再次下载相同的视频，会直接跳转下载列表，但是没有任务（但是任务数量是有的）
2.取消的任务直接移动到已完成，然后去已完成再删除一下才可以


[无法获取信息.txt](https://github.com/JiJiDown/Tracker/files/11007938/default.txt)
[无法获取信息的任务截图](https://user-images.githubusercontent.com/100948935/226094580-39915e3c-b777-4d82-934e-8477682ae7d8.png)

**Comment by KalunJ** [comment]
上述问题补充视频操作和日志
[debug.txt](https://github.com/JiJiDown/Tracker/files/11008050/debug.txt)

https://user-images.githubusercontent.com/100948935/226095541-e8aa2b17-1b75-4582-aee4-740e1d86bee6.mp4

**Comment by xiahuaijia** [comment]
请按要求提供日志, 如果确认问题解决可以关闭此问题
后续补充信息没有看到和问题相关的操作

**Comment by KalunJ** [comment]
https://pastebin.com/tUv2yXpm

**Comment by xiahuaijia** [comment]
问题已确认, 请更新后确认是否修复

**Comment by KalunJ** [comment]
根据提示已经更新，目前已经恢复了，谢谢答复！
