### ISSUE TITLE
核心似乎无法运行

### ISSUE THREAD

**Issue by Zmincrix** [JiJiDown/Tracker#15]
**描述错误**
![image](https://github.com/JiJiDown/Tracker/assets/35093819/8b86bae3-c2b6-455b-bf03-f00f6efb29d7)

![image](https://github.com/JiJiDown/Tracker/assets/35093819/cf7e37a0-fe9e-45f0-a85a-0b233551663b)

**软件信息**

 - 你使用的是什么系统: 
版本	Windows 11 企业版
版本	23H2
安装日期	‎2023/‎5/‎29
操作系统版本	25375.1
体验	Windows Feature Experience Pack 1000.25350.1000.0

 - 软件版本号: [JiJiDownCore git.r282.1f34dc07 windows/amd64 with go1.20.4]

**重现**
重现此行为的步骤:

1. 安装完毕
2. 双击“唧唧 Down 核心-快捷方式”
3. 黑色窗口一闪而逝
4. 调出debug模式，看到错误，一头雾水。

**预期行为**
正常运行

**附加日志**

[debug.txt](https://github.com/JiJiDown/Tracker/files/11646034/debug.txt)

```log
在此处添加有关该问题的日志。
```

**Comment by xiahuaijia** [comment]
1. 请不要尝试破解唧唧
2. 请使用本机在官网下载软件
3. 系统时间不对

**Comment by xiahuaijia** [comment]
此问题超过一个月没有新回复, 问题关闭
