### ISSUE TITLE
问题反馈：下载后无文件/未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by Doraney** [JiJiDown/Tracker#16]
我的系统：Windows 11
我的版本：git.r282.1f34dc07
视频编号: BV18h411T7GC
操作流程: 1080P视频文件
日志:
time="2023-06-21 10:43:35" level=info msg="Welcome to JiJiDownCore git.r282.1f34dc07 windows/amd64 with go1.20.4"
time="2023-06-21 10:43:35" level=info msg="Built on 2023-06-01 14:45:49"
time="2023-06-21 10:43:35" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-06-21 10:43:35" level=info msg="Configuration file location: C:\Users\CAR\AppData\Roaming\JiJiDown\config.yaml"
time="2023-06-21 10:43:35" level=info msg="JiJiDownCore Start..."
time="2023-06-21 10:43:35" level=debug msg=RefreshLoginStatus
time="2023-06-21 10:43:35" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-06-21 10:43:35" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-06-21 10:43:36" level=info msg="Update License"
time="2023-06-21 10:43:36" level=info msg="check update"
time="2023-06-21 10:43:36" level=info msg="ad loaded"
time="2023-06-21 10:43:36" level=info msg="missing file: ad77b4f135282580ac2df4f72314061183"
time="2023-06-21 10:43:36" level=error msg="download cache file fail: Get "[https://101.34.172.63/PC/ReWPF/ad/%E4%BD%A0%E4%BB%80%E4%B9%88%E6%97%B6%E5%80%99%E5%A5%B3%E8%A3%85.jpg\](https://101.34.172.63/PC/ReWPF/ad/%E4%BD%A0%E4%BB%80%E4%B9%88%E6%97%B6%E5%80%99%E5%A5%B3%E8%A3%85.jpg%5C)": tls: failed to verify certificate: x509: cannot validate certificate for 101.34.172.63 because it doesn't contain any IP SANs"
time="2023-06-21 10:43:36" level=error msg="open C:\Users\CAR\AppData\Roaming\JiJiDown\cache\ad77b4f135282580ac2df4f72314061183: The system cannot find the file specified."
time="2023-06-21 10:43:36" level=info msg="missing file: ad60aa7d4496416fedb391886416eab74f"
time="2023-06-21 10:43:36" level=error msg="download cache file fail: Get "[https://101.34.172.63/PC/ReWPF/ad/ios_tf.png\](https://101.34.172.63/PC/ReWPF/ad/ios_tf.png%5C)": tls: failed to verify certificate: x509: cannot validate certificate for 101.34.172.63 because it doesn't contain any IP SANs"
time="2023-06-21 10:43:36" level=error msg="open C:\Users\CAR\AppData\Roaming\JiJiDown\cache\ad60aa7d4496416fedb391886416eab74f: The system cannot find the file specified."
time="2023-06-21 10:43:36" level=info msg="JiJiDownCore Start Finish!"

**Comment by xiahuaijia** [comment]
操作流程和日志不符，请完善问题

**Comment by xiahuaijia** [comment]
未在时限内提供有效日志, 问题关闭
