### ISSUE TITLE
下载任务出错

### ISSUE THREAD

**Issue by o5-null** [JiJiDown/Tracker#18]
**描述错误**
任务下载出错，但是任务创建成功

问题描述不正确或缺少信息会要求补充信息, 7 天内未补充会被关闭问题。

**软件信息**

 - 你使用的是什么系统: windows/amd64 with go1.20.4
 - 软件版本号: git.r282.1f34dc07
 - https://www.bilibili.com/video/BV13k4y1u7VL

**重现**
重现此行为的步骤:

创建下载任务

**预期行为**
对您预期会发生什么的清晰简洁的描述。

**附加日志**

[日志获取方法请参阅 [唧唧 2.0 如何 Debug | 调试](http://client.jijidown.com/quick_start/how_to_debug/)

https://pastebin.com/TkUu80Rn

**Comment by xiahuaijia** [comment]
请完善问题

**Comment by xiahuaijia** [comment]
未在时限内提供有效日志, 问题关闭
