### ISSUE TITLE
grpc返回流被移除

### ISSUE THREAD

**Issue by o5-null** [JiJiDown/Tracker#19]
**描述错误**
清楚简明地描述错误是什么。

grpc返回流被移除

**软件信息**

 - windows/amd64 with go1.20.4
 - git.r282.1f34dc07
 -https://www.bilibili.com/video/BV1H841137XZ

**重现**
创建下载任务

**预期行为**
返回task_id

**附加日志**

https://pastebin.com/ADqAumFu

**Comment by xiahuaijia** [comment]
请完善问题描述

**Comment by xiahuaijia** [comment]
未在时限内提供有效日志, 问题关闭
