### ISSUE TITLE
暂停报错&可能受出国留学的影响造成的未知报错

### ISSUE THREAD

**Issue by KalunJ** [JiJiDown/Tracker#2]
**描述错误**
1.接上个反馈，我来git反馈挂了一个留学（科学clash v0.20.6 tun mode），反馈完回去看wpf ui不见了
2.于是新打开一个ui（到此核心应该还没崩，ui也没报错）解析之前的视频，多点了几次下载mp3，这时候下载列表没有任务，也没有其他反应，过了几秒，wpf停止运行，看后台核心报错。
3.重新打开核心，打开wpf，发现登录掉了，于是重新扫码登录。显示登录完成后，方框报错（未知错误）

4.还有个暂停报错，下载文件时候暂停会弹报错，日志见总日志最下边

**软件信息**

 - 你使用的是什么系统:windows10 22h2 x64
 - 软件版本号: git.r268.c713a0b2
 - (可选) 下载问题请添加视频地址: 这个应该不是局限某个视频

**重现**
重现此行为的步骤:

1. 正常使用解析下载
2. 出国
3. 点击之前解析的视频详情页
4. 点击下载mp3音频
5. 在下载页等待几秒后，核心报错退出

以下为登录报错，个人可能不能复现，说一下操作流程
6.  关闭wpf，重新打开核心，wpf
7.  点击登录
8.  扫码登录
9.  报错
10. 然后×掉弹错，也能用

暂停报错
挂不挂梯子都一样
1. 解析视频
2. 下载mp4/mp3
3. 任务列表暂停
4. 提示出错了，详情见日志

**预期行为**
对您预期会发生什么的清晰简洁的描述。

**附加日志**
[下载报错，登录报错.txt](https://github.com/JiJiDown/Tracker/files/10948533/default.txt)
https://pastebin.com/zHDQ7k4q

```log
在此处添加有关该问题的日志。
```

**Comment by xiahuaijia** [comment]
可能是网络问题请求失败导致的

无法确认该问题, 需要提供更多信息

**Comment by KalunJ** [comment]
回复个暂停报错吧

[暂停debug.txt](https://github.com/JiJiDown/Tracker/files/11008076/debug.txt)

https://user-images.githubusercontent.com/100948935/226096401-81128fc9-48c0-4d98-97bd-bb9f37b2889a.mp4

**Comment by xiahuaijia** [comment]
转换文件时, 不支持暂停

**Comment by KalunJ** [comment]
那个是临时发现的，后边有下载暂停报错
https://pastebin.com/N8ccuW4p

**Comment by KalunJ** [comment]
等待后续版本，over
