### ISSUE TITLE
1. 打开程序，显示报错 2. 无法登陆BILIBILI账户 3. 无法通过视频链接搜索视频，显示报错

### ISSUE THREAD

**Issue by 718791377** [JiJiDown/Tracker#20]
**描述错误**
清楚简明地描述错误是什么。

问题描述不正确或缺少信息会要求补充信息, 7 天内未补充会被关闭问题。

**软件信息**

 - 你使用的是什么系统: [例如: macOS / Linux / Windows] Windows 11
 - 软件版本号: [例如: git.r224.efbbba9] JiJiDown-git.r282.1f34dc07-windows-64-bit
 - (可选) 下载问题请添加视频地址: [例如:  ht<span>tps://</span>w<span>ww.</span>bilibili.com/video/av10086]

**重现**
重现此行为的步骤:

1. 打开程序，显示报错
2. 无法登陆BILIBILI账户
3. 无法通过视频链接搜索视频，显示报错

**预期行为**
对您预期会发生什么的清晰简洁的描述。

**附加日志**
以管理员身份启动程序显示报错：
JiJiDown.Core.SDK.dll 无法与 JiJiDownCore 通讯
![image](https://github.com/JiJiDown/Tracker/assets/33127863/37866a9d-7bf8-4aeb-aa8b-f481d2d8fcfc)
JiJiDownCore connection error
以管理员身份启动程序显示报错：
无法与唧唧核心通讯
检查核心是否还在运行
![image](https://github.com/JiJiDown/Tracker/assets/33127863/1a5ef7d2-4163-43ec-b091-0494b96060c6)
通过链接搜索视频显示报错：
JiJiDown.Core.SDK.dll 无法与 JiJiDownCore 通讯
![image](https://github.com/JiJiDown/Tracker/assets/33127863/43ead769-b835-40b7-8096-32f9c7b852a6)

1.检查 JiJiDownCore 是否还在运行
2.检查端口是否监听成功
3.检查配置文件

1.检查 JiJiDownCore 是否还在运行
2.检查端口是否监听成功
3.检查配置文件

日志获取方法请参阅 [唧唧 2.0 如何 Debug | 调试](http://client.jijidown.com/quick_start/how_to_debug/)

日志太长可以使用 pastebin 分享日志

```log
在此处添加有关该问题的日志。
```

**Comment by xiahuaijia** [comment]
请按要求提供日志

**Comment by xiahuaijia** [comment]
未在时限内提供有效日志, 问题关闭
