### ISSUE TITLE
下载视频报错：GetVideoList function not allowed

### ISSUE THREAD

**Issue by ten-years-of-invitation** [JiJiDown/Tracker#22]
**描述错误**
复制链接下载视频报错
GrpcAPI() 错误:
错误代码: 10104
详细信息: GetVideoList function not allowed

**软件信息**

 - 你使用的是什么系统: Windows 11 23H2
 - 软件版本号: git.r294.c10ef218

**重现**
重现此行为的步骤:
1.B站点击视频复制链接
2.jijidown弹出通知，获取到该地址链接
3.点击jijidown发出来的通知
4.自动打开UI，出现错误：GetVideoList function not allowed

**预期行为**

**附加日志**

日志获取方法请参阅 [唧唧 2.0 如何 Debug | 调试](http://client.jijidown.com/quick_start/how_to_debug/)

日志太长可以使用 pastebin 分享日志

```log
time="2023-10-09 09:55:04" level=info msg="JiJiDownCore Start Finish!"
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Task/Notification' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Status/CheckUpdate' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:50" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:55" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
```

**Comment by xiahuaijia** [comment]
请按要求提供日志

**Comment by ten-years-of-invitation** [comment]
‘’‘
time="2023-10-09 09:55:03" level=info msg="Welcome to JiJiDownCore git.r294.c10ef218 windows/amd64 with go1.21.2"
time="2023-10-09 09:55:03" level=info msg="Built on 2023-10-07 19:40:00"
time="2023-10-09 09:55:03" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-10-09 09:55:03" level=info msg="Configuration file location: C:\\Users\\Administrator\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-10-09 09:55:03" level=info msg="JiJiDownCore Start..."
time="2023-10-09 09:55:03" level=debug msg=RefreshLoginStatus
time="2023-10-09 09:55:03" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-10-09 09:55:03" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-10-09 09:55:03" level=error msg="RefreshLoginStatus error: code -101, message: 账号未登录"
time="2023-10-09 09:55:03" level=info msg="Update License"
time="2023-10-09 09:55:04" level=info msg="check update"
time="2023-10-09 09:55:04" level=info msg="ad loaded"
time="2023-10-09 09:55:04" level=info msg="JiJiDownCore Start Finish!"
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Task/Notification' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Status/CheckUpdate' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:50" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:55" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
’‘’
![image](https://github.com/JiJiDown/Tracker/assets/108484816/ac4cd45e-399a-4d2d-b41e-3d5b08094d79)

**Comment by ten-years-of-invitation** [comment]
`
time="2023-10-09 09:55:03" level=info msg="Welcome to JiJiDownCore git.r294.c10ef218 windows/amd64 with go1.21.2"
time="2023-10-09 09:55:03" level=info msg="Built on 2023-10-07 19:40:00"
time="2023-10-09 09:55:03" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-10-09 09:55:03" level=info msg="Configuration file location: C:\\Users\\Administrator\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-10-09 09:55:03" level=info msg="JiJiDownCore Start..."
time="2023-10-09 09:55:03" level=debug msg=RefreshLoginStatus
time="2023-10-09 09:55:03" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-10-09 09:55:03" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-10-09 09:55:03" level=error msg="RefreshLoginStatus error: code -101, message: 账号未登录"
time="2023-10-09 09:55:03" level=info msg="Update License"
time="2023-10-09 09:55:04" level=info msg="check update"
time="2023-10-09 09:55:04" level=info msg="ad loaded"
time="2023-10-09 09:55:04" level=info msg="JiJiDownCore Start Finish!"
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Task/Notification' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Status/CheckUpdate' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:50" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:55" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
time="2023-10-09 10:14:20" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 10:14:21" level=error msg="GetVideoList function not allowed"
`

**Comment by ten-years-of-invitation** [comment]
time="2023-10-09 09:55:03" level=info msg="Welcome to JiJiDownCore git.r294.c10ef218 windows/amd64 with go1.21.2"
time="2023-10-09 09:55:03" level=info msg="Built on 2023-10-07 19:40:00"
time="2023-10-09 09:55:03" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-10-09 09:55:03" level=info msg="Configuration file location: C:\\Users\\Administrator\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-10-09 09:55:03" level=info msg="JiJiDownCore Start..."
time="2023-10-09 09:55:03" level=debug msg=RefreshLoginStatus
time="2023-10-09 09:55:03" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-10-09 09:55:03" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-10-09 09:55:03" level=error msg="RefreshLoginStatus error: code -101, message: 账号未登录"
time="2023-10-09 09:55:03" level=info msg="Update License"
time="2023-10-09 09:55:04" level=info msg="check update"
time="2023-10-09 09:55:04" level=info msg="ad loaded"
time="2023-10-09 09:55:04" level=info msg="JiJiDownCore Start Finish!"
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Task/Notification' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Status/CheckUpdate' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:50" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:55" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
time="2023-10-09 10:14:20" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 10:14:21" level=error msg="GetVideoList function not allowed"

**Comment by ten-years-of-invitation** [comment]
```
time="2023-10-09 09:55:03" level=info msg="Welcome to JiJiDownCore git.r294.c10ef218 windows/amd64 with go1.21.2"
time="2023-10-09 09:55:03" level=info msg="Built on 2023-10-07 19:40:00"
time="2023-10-09 09:55:03" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-10-09 09:55:03" level=info msg="Configuration file location: C:\\Users\\Administrator\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-10-09 09:55:03" level=info msg="JiJiDownCore Start..."
time="2023-10-09 09:55:03" level=debug msg=RefreshLoginStatus
time="2023-10-09 09:55:03" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-10-09 09:55:03" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-10-09 09:55:03" level=error msg="RefreshLoginStatus error: code -101, message: 账号未登录"
time="2023-10-09 09:55:03" level=info msg="Update License"
time="2023-10-09 09:55:04" level=info msg="check update"
time="2023-10-09 09:55:04" level=info msg="ad loaded"
time="2023-10-09 09:55:04" level=info msg="JiJiDownCore Start Finish!"
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Task/Notification' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=debug msg="> Received '/jijidown.core.Status/CheckUpdate' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:50" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:55" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 09:56:56" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
time="2023-10-09 10:14:20" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=debug msg="> Received '/jijidown.core.Bvideo/Info' RPC"
> Received: os => [Windows 11 10.0.22631.0 x64], device => [AMD Ryzen 7 5800H with Radeon Graphics  (8C/16T)]
time="2023-10-09 10:14:21" level=warning msg="GetVideoList function not allowed"
time="2023-10-09 10:14:21" level=error msg="GetVideoList function not allowed"
```
日志显示内容就这么多

**Comment by xiahuaijia** [comment]
从日志中可以看出并未登录账号

```
time="2023-10-09 09:55:03" level=error msg="RefreshLoginStatus error: code -101, message: 账号未登录"
time="2023-10-09 09:56:35" level=error msg="User no login"
time="2023-10-09 09:56:56" level=error msg="GetVideoList function not allowed"
```


> 6. 使用 扫码登录 账号 (登录后才可尝鲜)

根据官网**新手上路**教程中所说, 需要登陆后才可使用
