### ISSUE TITLE
多个视频同时下载，只有最后下载的视频能成功

### ISSUE THREAD

**Issue by shikai-123** [JiJiDown/Tracker#24]
**描述错误**
多个任务同时下载有问题啊 先后下载两个文件  最后只能有最后那个文件存在，前面的那个文件没了

**软件信息**

 - windows10专业版22H2

**重现**
1、点击下载a
2、再下载b。
3、最后只能下载的b。a缺失。
4、我试了两次都是这样
5、从log中看，两个文件都是成功下载的，但是a文件貌似在从temp拷贝的时候出现问题。应该和ffmpeg有关系。这个库我了解的不多。具体看log把
6、再次下载a的时候。提示a已经下载成功了

**预期行为**
先后下载ab，应该两个都能下载下来。而不是只有b。

**附加日志**
time="2023-11-22 22:15:48" level=debug msg="104.20 MiB/105.00 MiB 326.35 KiB/s ETA: 3 秒"
time="2023-11-22 22:15:48" level=debug msg="97.83 MiB/120.87 MiB 2.23 MiB/s ETA: 10 秒"
time="2023-11-22 22:15:48" level=debug msg="104.22 MiB/105.00 MiB 326.35 KiB/s ETA: 2 秒"
time="2023-11-22 22:15:48" level=debug msg="98.61 MiB/120.87 MiB 2.23 MiB/s ETA: 10 秒"
time="2023-11-22 22:15:48" level=debug msg="104.23 MiB/105.00 MiB 326.35 KiB/s ETA: 2 秒"
time="2023-11-22 22:15:48" level=debug msg="JDM: session: order: 09 task end"
time="2023-11-22 22:15:48" level=debug msg="99.39 MiB/120.87 MiB 745.63 KiB/s ETA: 30 秒"
time="2023-11-22 22:15:48" level=debug msg="104.36 MiB/105.00 MiB 326.35 KiB/s ETA: 2 秒"
time="2023-11-22 22:15:48" level=debug msg="99.65 MiB/120.87 MiB 822.47 KiB/s ETA: 26 秒"
time="2023-11-22 22:15:48" level=debug msg="104.50 MiB/105.00 MiB 355.18 KiB/s ETA: 1 秒"
time="2023-11-22 22:15:49" level=debug msg="99.95 MiB/120.87 MiB 822.47 KiB/s ETA: 26 秒"
time="2023-11-22 22:15:49" level=debug msg="104.62 MiB/105.00 MiB 355.18 KiB/s ETA: 1 秒"
time="2023-11-22 22:15:49" level=debug msg="100.28 MiB/120.87 MiB 889.75 KiB/s ETA: 24 秒"
time="2023-11-22 22:15:49" level=debug msg="104.78 MiB/105.00 MiB 355.18 KiB/s ETA: 1 秒"
time="2023-11-22 22:15:49" level=debug msg="100.62 MiB/120.87 MiB 889.75 KiB/s ETA: 23 秒"
time="2023-11-22 22:15:49" level=debug msg="104.97 MiB/105.00 MiB 355.18 KiB/s ETA: 0 秒"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: order: 02 task end"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: concatenating: 0"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: concatenating: 1"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: concatenating: 2"
time="2023-11-22 22:15:49" level=debug msg="101.00 MiB/120.87 MiB 889.75 KiB/s ETA: 23 秒"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: concatenating: 3"
time="2023-11-22 22:15:49" level=debug msg="JDM: session: 12d0a4bb9c5d41641c4762c69dcfcdde download session finish"
time="2023-11-22 22:15:49" level=debug msg="JDM: JDMTask finish"
time="2023-11-22 22:15:49" level=debug msg="getFFmpegPath: use run directory FFmpeg"
time="2023-11-22 22:15:49" level=debug msg="./ffmpeg [-i C:\\Users\\Star\\AppData\\Local\\Temp\\JiJiDown\\f8ec974e815ecb1dc201ddc53a95022e -i C:\\Users\\Star\\AppData\\Local\\Temp\\JiJiDown\\12d0a4bb9c5d41641c4762c69dcfcdde -vcodec copy -acodec copy C:\\Users\\Star\\Desktop\\代码随想\\链表：6.环形链表|| (高清 1080P, AVC, 极高音质, WEB).mp4 -y]"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug: ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   built with gcc 10-win32 (GCC) 20220113"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   configuration: --arch=x86 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --enable-small --disable-autodetect --disable-debug --disable-network --disable-pthreads --disable-w32threads --disable-doc --disable-ffplay --disable-ffprobe --disable-decoders --enable-decoder='aac,aac_fixed' --disable-encoders --enable-libmp3lame --enable-encoder=libmp3lame --disable-hwaccels --disable-parsers --disable-demuxers --enable-demuxer=mov --disable-muxers --enable-muxer='mp4,mp3' --disable-protocols --enable-protocol=file --disable-filters --disable-bsfs --disable-indevs --disable-outdevs"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libavutil      57. 28.100 / 57. 28.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libavcodec     59. 37.100 / 59. 37.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libavformat    59. 27.100 / 59. 27.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libavdevice    59.  7.100 / 59.  7.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libavfilter     8. 44.100 /  8. 44.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libswscale      6.  7.100 /  6.  7.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   libswresample   4.  7.100 /  4.  7.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\\Users\\Star\\AppData\\Local\\Temp\\JiJiDown\\f8ec974e815ecb1dc201ddc53a95022e':"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Metadata:"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     major_brand     : iso5"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     minor_version   : 1"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     compatible_brands: avc1iso5dsmsmsixdash"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     encoder         : Lavf58.29.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     description     : Packed by Bilibili XCoder v2.0.2"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Duration: 00:19:50.71, start: 0.043000, bitrate: 607 kb/s"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Stream #0:0[0x1](und): Video: h264 (avc1 / 0x31637661), none, 1920x1080, 1 kb/s, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 16k tbn (default)"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     Metadata:"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:       handler_name    : VideoHandler"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:       vendor_id       : [0][0][0][0]"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug: Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\\Users\\Star\\AppData\\Local\\Temp\\JiJiDown\\12d0a4bb9c5d41641c4762c69dcfcdde':"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Metadata:"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     major_brand     : iso5"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     minor_version   : 1"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     compatible_brands: avc1iso5dsmsmsixdash"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     encoder         : Lavf58.29.100"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     description     : Packed by Bilibili XCoder v2.0.2"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Duration: 00:19:50.74, start: 0.000000, bitrate: 132 kb/s"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:   Stream #1:0[0x2](und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 0 kb/s (default)"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:     Metadata:"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:       handler_name    : SoundHandler"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug:       vendor_id       : [0][0][0][0]"
time="2023-11-22 22:15:49" level=debug msg="FFmpeg debug: C:\\Users\\Star\\Desktop\\代码随想\\链表：6.环形链表|| (高 清 1080P, AVC, 极高音质, WEB).mp4: Invalid argument"
time="2023-11-22 22:15:49" level=debug msg="ProcessVideoWithffmpeg complete"
time="2023-11-22 22:15:49" level=info msg="TaskComplete: 440e5a2ebb084695a93dca20e1e5f14c"
time="2023-11-22 22:15:49" level=debug msg="101.40 MiB/120.87 MiB 1001.71 KiB/s ETA: 20 秒"
time="2023-11-22 22:15:50" level=debug msg="101.69 MiB/120.87 MiB 1001.71 KiB/s ETA: 20 秒"
time="2023-11-22 22:15:50" level=debug msg="101.89 MiB/120.87 MiB 1.08 MiB/s ETA: 18 秒"
time="2023-11-22 22:15:50" level=debug msg="102.36 MiB/120.87 MiB 1.08 MiB/s ETA: 17 秒"
time="2023-11-22 22:15:50" level=debug msg="102.84 MiB/120.87 MiB 1.08 MiB/s ETA: 17 秒"
time="2023-11-22 22:15:50" level=debug msg="103.31 MiB/120.87 MiB 1.20 MiB/s ETA: 15 秒"
time="2023-11-22 22:15:51" level=debug msg="103.62 MiB/120.87 MiB 1.20 MiB/s ETA: 14 秒"
time="2023-11-22 22:15:51" level=debug msg="104.14 MiB/120.87 MiB 1.38 MiB/s ETA: 12 秒"
time="2023-11-22 22:15:51" level=debug msg="104.75 MiB/120.87 MiB 1.38 MiB/s ETA: 12 秒"
time="2023-11-22 22:15:51" level=debug msg="JDM: session: order: 00 task end"

```log
log如上
```

**Comment by xiahuaijia** [comment]
请按要求提供完整日志
请按要求描述问题
