### ISSUE TITLE
安装过程中，出现msg="missing file: bgimage"报错，已上传Debug日志，无法解决问题

### ISSUE THREAD

**Issue by chaozhangGS** [JiJiDown/Tracker#25]
Windows
 - 软件版本号: [git.r303.11c0f390]

【唧唧核心 Debug】
time="2023-12-13 10:14:25" level=info msg="Welcome to JiJiDownCore git.r303.11c0f390 windows/amd64 with go1.21.4"
time="2023-12-13 10:14:25" level=info msg="Built on 2023-12-03 21:13:44"
time="2023-12-13 10:14:25" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-12-13 10:14:25" level=info msg="Configuration file location: C:\\Users\\Admin\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-12-13 10:14:25" level=info msg="JiJiDownCore Start..."
time="2023-12-13 10:14:25" level=info msg="External controller gRPC listening at 127.0.0.1:8808"
time="2023-12-13 10:14:25" level=info msg="External controller RESTful API listening at: 127.0.0.1:64001"
time="2023-12-13 10:14:25" level=info msg="External controller gRPC-web listening at 127.0.0.1:4100"
time="2023-12-13 10:14:25" level=info msg="Update License"
time="2023-12-13 10:14:26" level=info msg="check update"
time="2023-12-13 10:14:26" level=warning msg="missing file: bgimage"
time="2023-12-13 10:14:26" level=info msg="ad loaded"
time="2023-12-13 10:14:26" level=info msg="JiJiDownCore Start Finish!"
请按任意键继续. . .

【已安装dotnet-sdk-8.0.100-win-x64.exe框架，这个应该就是.NET 8.0 SDK (v8.0.100) - Windows x64框架吧，cmd输入dotnet 回车有输出】

【配置文件config.yaml】
log-level: debug
external-controller-port:
    grpc: 8808
    grpc-web: 4100
    restful-api: 64001
download-task:
    max-task: 2
    download-speed-limit: 0
jdm:
    max-retry: 5
    retry-wait: 10
    session-workers: 1
    part-workers: 5
    min-split-size: 5
    proxy-addr: ""
    check-best-mirror: true
    cache-in-ram: false
    cache-in-ram-limit: 500
    insecure-skip-verify: false
    custom-root-certificates: ""
    
 【检测 唧唧核心是否运行】【正在运行】
 C:\Users\Admin>wmic process where (name="JiJiDownCore-win64.exe") get ProcessId,Name
Name                    ProcessId
JiJiDownCore-win64.exe  21688

【检测 端口】【输出结果与qqdoc文档不一致】【防火墙建立开放64000端口规则，无法解决】
C:\Users\Admin>netstat -an | findstr "64000 64001"
  TCP    127.0.0.1:4190         127.0.0.1:64001        ESTABLISHED
  TCP    127.0.0.1:64001        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:64001        127.0.0.1:4190         ESTABLISHED

【结果：仍然无法下载视频】
![image](https://github.com/JiJiDown/Tracker/assets/78540610/c13acb1d-71fc-4004-9c36-4fa16260c04e)

**Comment by xiahuaijia** [comment]
配置文件中 grpc 端口号错误

**Comment by zhangdudu0** [comment]
> 配置文件中 grpc 端口号错误

好滴非常感谢！我已经完成了，但是有个问题，《我登录一个账户后，好像无法退出。》
《配置文件中 grpc 端口号错误 应该如何解决》
编辑C:\Users\Admin\AppData\Roaming\JiJiDown\config.yaml，将grpc: 8808改为4000。
然后双击C:\Program Files\JiJiDown\早期测试启动核心-调试.bat程序，进行调试
发现4000端口被占用
打开cmd窗口输入netstat -ano | findstr :4000，发现4000端口下绑定了一个5816 PID进程
于是打开“任务管理器”，点击“详细信息”，点击PID进行排序，找到5816进程对应的程序，右键5816进程，结束任务
双击C:\Program Files\JiJiDown\早期测试启动核心-调试.bat程序，进行调试
发现没有出现报错，退出后双击C:\Program Files\JiJiDown\早期测试启动核心并隐藏黑色窗口-启动.bat
打开cmd窗口，wmic process where (name="JiJiDownCore-win64.exe") get ProcessId,Name，查看是否启动唧唧核心
启动后，双击C:\Program Files\JiJiDown\JiJiDownForReWPF.exe，打开UI界面，点击登录
打开自己已经登录的网页版b站，按F12，点击《网络》，刷新一下网页，点击《文档/Doc》，找到《?spm_id_from=333.337.0.0》，再找到cookies，复制下来
到唧唧UI界面，将cookies粘贴进去，点击导入cookies，完成登录

**Comment by chaozhangGS** [comment]
好滴非常感谢！我已经解决了配置文件中 grpc 端口号错误的问题
《配置文件中 grpc 端口号错误 应该如何解决》
编辑C:\Users\Admin\AppData\Roaming\JiJiDown\config.yaml，将grpc: 8808改为4000。
然后双击C:\Program Files\JiJiDown\早期测试启动核心-调试.bat程序，进行调试
发现4000端口被占用
打开cmd窗口输入netstat -ano | findstr :4000，发现4000端口下绑定了一个5816 PID进程
于是打开“任务管理器”，点击“详细信息”，点击PID进行排序，找到5816进程对应的程序，右键5816进程，结束任务
双击C:\Program Files\JiJiDown\早期测试启动核心-调试.bat程序，进行调试
发现没有出现报错，退出后双击C:\Program Files\JiJiDown\早期测试启动核心并隐藏黑色窗口-启动.bat
打开cmd窗口，wmic process where (name="JiJiDownCore-win64.exe") get ProcessId,Name，查看是否启动唧唧核心
启动后，双击C:\Program Files\JiJiDown\JiJiDownForReWPF.exe，打开UI界面，点击登录
打开自己已经登录的网页版b站，按F12，点击《网络》，刷新一下网页，点击《文档/Doc》，找到《?spm_id_from=333.337.0.0》，再找到cookies，复制下来
到唧唧UI界面，将cookies粘贴进去，点击导入cookies，完成登录

**Comment by chaozhangGS** [comment]
但是有两个问题，《我登录一个账户后，好像无法退出》
```
> Received: os => [Windows 10 22H2 x64], device => [Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz  (6C/12T)]
time="2023-12-15 11:42:11" level=error msg="User already logged in"
time="2023-12-15 11:42:16" level=debug msg="> Received '/jijidown.core.User/Info' RPC"
```
《还是无法下载》
《视频链接：https://www.bilibili.com/video/BV1JG411S7ne》
```
> Received: os => [Windows 10 22H2 x64], device => [Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz  (6C/12T)]
time="2023-12-15 11:42:11" level=debug msg="> Received '/jijidown.core.User/ImportCookie' RPC"
> Received: os => [Windows 10 22H2 x64], device => [Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz  (6C/12T)]
time="2023-12-15 11:42:54" level=debug msg="> Received '/jijidown.core.Bvideo/CheckContent' RPC"
> Received: os => [Windows 10 22H2 x64], device => [Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz  (6C/12T)]
time="2023-12-15 11:44:13" level=info msg="Update License"
```

**Comment by chaozhangGS** [comment]
进行了可用性测序
![image](https://github.com/JiJiDown/Tracker/assets/78540610/4de1b73b-5a4b-4624-a39a-d87ed90eba23)

**Comment by xiahuaijia** [comment]
此问题已解决

有其他问题请单独提出
