### ISSUE TITLE
端口与福昕阅读器冲突

### ISSUE THREAD

**Issue by Marsopera** [JiJiDown/Tracker#26]
**描述错误**

弹窗提示
JiJiDown.Core.SDK.dll 无法与 JiJiDownCore 通讯
1.检查 JiJiDownCore 是否还在运行
2.检查端口是否监听成功
3.检查配置文件

**软件信息**

 - 你使用的是什么系统:  Win10 
 - 软件版本号:  git.r305.14b02996 windows/amd64 with go1.22.0
 - (可选) 下载问题请添加视频地址: 与此无关

**重现**
重现此行为的步骤:

1.安装福昕阅读器
2.命令行手动启动JiJiDownCore.exe，或采用调试.bat启动，可以看到
```
time="2024-03-18 14:28:20" level=fatal msg="External controller gRPC listen error: listen tcp 127.0.0.1:4000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```
3.查询4000端口的占用情况，发现是`FoxitProtect.exe`，这是福昕阅读器的文档安全防护进程。

**预期行为**
对您预期会发生什么的清晰简洁的描述。

安装有福昕阅读器的电脑大概率会发生此问题。

**附加日志**

```log
time="2024-03-18 14:28:20" level=info msg="Welcome to JiJiDownCore git.r305.14b02996 windows/amd64 with go1.22.0"
time="2024-03-18 14:28:20" level=info msg="Built on 2024-02-29 13:17:29"
time="2024-03-18 14:28:20" level=info msg="Copyright 2014-2024 - JiJiDown.com"
time="2024-03-18 14:28:20" level=info msg="Configuration file location: C:\\######\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2024-03-18 14:28:20" level=fatal msg="External controller gRPC listen error: listen tcp 127.0.0.1:4000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

**Comment by xiahuaijia** [comment]
`http://client.jijidown.com/quick_start/configuration/#external-controller-port-grpc`

根据官网描述 
>  0 则关闭此功能, 不监听任何端口。

**Comment by Marsopera** [comment]
> `http://client.jijidown.com/quick_start/configuration/#external-controller-port-grpc`
> 
> 根据官网描述
> 
> > 0 则关闭此功能, 不监听任何端口。

get√
