### ISSUE TITLE
建议把linux的核心启动会删除tmp文件加入文档, 太抽象了 : D

### ISSUE THREAD

**Issue by Alic-Li** [JiJiDown/Tracker#29]
我的挂载目录全没了。。。还好没有重要文件

**Comment by xiahuaijia** [comment]
请按要求提交问题 需要提供更多信息

**Comment by Alic-Li** [comment]
搓配置文件的时候，他的tmp挂载目录挂载点会每次启动时清除这个挂载点目录下所有的文件，希望别人不要踩坑

**Comment by xiahuaijia** [comment]
> ## What is a Temp directory? / 什么是临时目录？
> The temp directory, short for temporary directory, is a folder on your computer where temporary files are stored. These temporary files are created and used by various applications and processes during their operation. The temp directory is typically used to store data that is only needed for a short period of time and can be deleted once it is no longer required.
> 
> temp 是临时目录的缩写，是计算机上存储临时文件的文件夹。这些临时文件由各种应用程序和进程在运行过程中创建和使用。临时目录通常用于存储仅在短时间内需要的数据，一旦不再需要，就可以删除。

> ## Can I change the location of the temp directory? / 我可以更改临时目录的位置吗？
> Yes, it is possible to change the location of the temp directory on your computer. However, this process involves modifying system settings and should be done with caution. It is generally recommended to keep the temp directory in its default location unless you have specific reasons and knowledge to change it. Modifying system settings without proper understanding can lead to unexpected issues.
> 
> 是的，您可以更改计算机上临时目录的位置。但是，此过程涉及修改系统设置，应谨慎操作。通常建议将临时目录保留在其默认位置，除非您有特定原因和知识来更改它。在没有正确理解的情况下修改系统设置可能会导致意外问题。



综上所述软件设计没有任何问题, 清理软件使用的 temp 是符合设计标准的. 如果因自己原因修改了 temp 目录位置, 请确保有足够的知识来更改它.

这不是一个有效的错误报告
