### ISSUE TITLE
无法与唧唧核心通讯

### ISSUE THREAD

**Issue by moke233** [JiJiDown/Tracker#8]
**描述错误**
今天在官网上下好2.0版本之后打开核心再开ui提示报错
![122](https://user-images.githubusercontent.com/58896274/232232923-fc81cc63-4b2a-41f7-8e0d-9f9d9b8309af.png)
之后试着把warning改成debug也是同样的问题
jijicore没有在运行
![455](https://user-images.githubusercontent.com/58896274/232233320-a57b74a5-586f-484f-9379-04220c75caaf.png)
![456](https://user-images.githubusercontent.com/58896274/232233411-3521c620-f7a5-46f7-a7de-b0624cedb8f5.png)

**软件信息**

 - 你使用的是什么系统: Win 11 22h2（22621.1413）
 - 软件版本号: git.r279.6fb8d2cb

**重现**
重现此行为的步骤:

点开软件即报错

**预期行为**
对您预期会发生什么的清晰简洁的描述。

**附加日志**
time="2023-04-15 23:09:25" level=info msg="Welcome to JiJiDownCore git.r279.6fb8d2cb windows/amd64 with go1.20.3"
time="2023-04-15 23:09:25" level=info msg="Built on 2023-04-15 12:32:59"
time="2023-04-15 23:09:25" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-04-15 23:09:25" level=info msg="Configuration file location: C:\\Users\\23507\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-04-15 23:09:25" level=info msg="JiJiDownCore Start..."
time="2023-04-15 23:09:25" level=info msg="RESTful API listening at: 127.0.0.1:64001"
time="2023-04-15 23:09:25" level=info msg="External controller gRPC listening at 127.0.0.1:64000"
time="2023-04-15 23:09:25" level=fatal msg="nice try"

**Comment by xiahuaijia** [comment]
感谢反馈, 唧唧 2.0 完全适配 Windows 11. 
这个应该是系统时间有误差导致的. 在 `系统设置` -> `时间和语言` -> `日期和时间` -> `同步`

**Comment by moke233** [comment]
感谢回复，我看了下时间是对的（重新同步过还是不行），应该是我自己电脑的问题，后面我用了其他的电脑试了一下（也是win 11），发现可以正常使用

**Comment by ZhangQingsen** [comment]
time="2023-04-20 18:31:40" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
time="2023-04-20 18:31:40" level=info msg="Built on 2023-04-19 19:48:56"
time="2023-04-20 18:31:40" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-04-20 18:31:40" level=info msg="Configuration file location: C:\\Users\\XXXXXXX\\AppData\\Roaming\\JiJiDown\\config.yaml"
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
time="2023-04-20 18:31:50" level=error msg="User no login"
time="2023-04-20 18:31:50" level=error msg="GetFromRestClient resp error: Get \"https://api.bilibili.com/x/web-interface/nav\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2023-04-20 18:31:50" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input"
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
time="2023-04-20 18:31:52" level=warning msg="GetVideoList function not allowed"
time="2023-04-20 18:31:52" level=error msg="GetVideoList function not allowed"


从错误信息来看是一样的问题

\-------------------------------------------------------------------------------------------------------------------------------------------
又尝试了几遍
都是先启动core再启动WebUI
\-------------------------------------------------------------------------------------------------------------------------------------------
然后经常(几乎每次)都会在获取下载链接是core闪退
排查报错信息如下
time="2023-04-20 19:18:13" level=error msg="getVideoDownloadInfoForWEB json error: unexpected end of JSON input"
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]

看来我的问题和楼主的不一样，我的问题是**unexpected end of JSON input**后似乎自动执行了什么WebUI操作，会导致core闪退

**Comment by moke233** [comment]
time="2023-04-21 22:44:39" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
time="2023-04-21 22:44:39" level=info msg="Built on 2023-04-19 19:48:56"
time="2023-04-21 22:44:39" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-04-21 22:44:39" level=info msg="Configuration file location: C:\\Users\\23507\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-04-21 22:44:39" level=fatal msg="External controller gRPC listen error: listen tcp 127.0.0.1:64000: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
请按任意键继续. . .

-----------------------------------------------------------------------------

我和你的一个有点不一样，今天试了下更到最新的2.0，报错信息上没看到访问到外网，应该是在本地监听端口报错之后core闪退，之前有说过应该是我的问题是因为我电脑之前开了代理之后清不干净，电脑有些应用不走代理

**Comment by KalunJ** [comment]
> time="2023-04-20 18:31:40" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3" time="2023-04-20 18:31:40" level=info msg="Built on 2023-04-19 19:48:56" time="2023-04-20 18:31:40" level=info msg="Copyright 2014-2023 - JiJiDown.com" time="2023-04-20 18:31:40" level=info msg="Configuration file location: C:\Users\XXXXXXX\AppData\Roaming\JiJiDown\config.yaml" > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)] > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)] > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)] time="2023-04-20 18:31:50" level=error msg="User no login" time="2023-04-20 18:31:50" level=error msg="GetFromRestClient resp error: Get "[https://api.bilibili.com/x/web-interface/nav\](https://api.bilibili.com/x/web-interface/nav%5C)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" time="2023-04-20 18:31:50" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input" > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)] > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)] time="2023-04-20 18:31:52" level=warning msg="GetVideoList function not allowed" time="2023-04-20 18:31:52" level=error msg="GetVideoList function not allowed"
> 
> 从错误信息来看是一样的问题
> 
> ------------------------------------------------------------------------------------------------------------------------------------------- 又尝试了几遍 都是先启动core再启动WebUI ------------------------------------------------------------------------------------------------------------------------------------------- 然后经常(几乎每次)都会在获取下载链接是core闪退 排查报错信息如下 time="2023-04-20 19:18:13" level=error msg="getVideoDownloadInfoForWEB json error: unexpected end of JSON input" > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (6C/12T)]
> 
> 看来我的问题和楼主的不一样，我的问题是**unexpected end of JSON input**后似乎自动执行了什么WebUI操作，会导致core闪退

没登陆

**Comment by ZhangQingsen** [comment]
> 没登陆

从WebUI来看我是登录BiliBili账号的，有的时候会登录失败，core打印如下:
>time="2023-04-23 18:29:20" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
time="2023-04-23 18:29:20" level=info msg="Built on 2023-04-19 19:48:56"
time="2023-04-23 18:29:20" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-04-23 18:29:20" level=info msg="Configuration file location: C:\\Users\\XXXXXXX\\AppData\\Roaming\\JiJiDown\\config.yaml"
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
\> Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
time="2023-04-23 18:29:27" level=error msg="User no login"
time="2023-04-23 18:29:30" level=error msg="GetFromRestClient resp error: Get \"https://api.bilibili.com/x/web-interface/nav\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2023-04-23 18:29:30" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input"

但是这个问题重启能解决。

我怀疑我的core闪退的问题可能源自我家网络的问题。前两天拒绝移动的改套餐电话后网络一直加载巨慢，但下载速度没有问题。我目前还没排查出来是哪里的问题，只能怀疑移动运营商。jiji1就会网络不好的时候表现不好，可能jiji2继承了这一点。

**Comment by KalunJ** [comment]
> > 没登陆
> 
> 从WebUI来看我是登录BiliBili账号的，有的时候会登录失败，core打印如下:
> 
> > time="2023-04-23 18:29:20" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
> > time="2023-04-23 18:29:20" level=info msg="Built on 2023-04-19 19:48:56"
> > time="2023-04-23 18:29:20" level=info msg="Copyright 2014-2023 - JiJiDown.com"
> > time="2023-04-23 18:29:20" level=info msg="Configuration file location: C:\Users\XXXXXXX\AppData\Roaming\JiJiDown\config.yaml"
> > > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
> > > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
> > time="2023-04-23 18:29:27" level=error msg="User no login"
> > time="2023-04-23 18:29:30" level=error msg="GetFromRestClient resp error: Get "[https://api.bilibili.com/x/web-interface/nav\](https://api.bilibili.com/x/web-interface/nav%5C)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> > time="2023-04-23 18:29:30" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input"
> 
> 但是这个问题重启能解决。

登录失败换个网络环境，IP用的人太多或者不稳定会有问题，还有把config.yml删除重装重登试试（清除登录状态重登）

**Comment by KalunJ** [comment]
> 

最后换个DNS试试 例如223.5.5.5

**Comment by KalunJ** [comment]
> > 没登陆
> 
> 从WebUI来看我是登录BiliBili账号的，有的时候会登录失败，core打印如下:
> 
> > time="2023-04-23 18:29:20" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
> > time="2023-04-23 18:29:20" level=info msg="Built on 2023-04-19 19:48:56"
> > time="2023-04-23 18:29:20" level=info msg="Copyright 2014-2023 - JiJiDown.com"
> > time="2023-04-23 18:29:20" level=info msg="Configuration file location: C:\Users\XXXXXXX\AppData\Roaming\JiJiDown\config.yaml"
> > > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
> > > Received: os => [Windows 11 22H2 x64], device => [Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz  (6C/12T)]
> > time="2023-04-23 18:29:27" level=error msg="User no login"
> > time="2023-04-23 18:29:30" level=error msg="GetFromRestClient resp error: Get "[https://api.bilibili.com/x/web-interface/nav\](https://api.bilibili.com/x/web-interface/nav%5C)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> > time="2023-04-23 18:29:30" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input"
> 
> 但是这个问题重启能解决。
> 
> 我怀疑我的core闪退的问题可能源自我家网络的问题。前两天拒绝移动的改套餐电话后网络一直加载巨慢，但下载速度没有问题。我目前还没排查出来是哪里的问题，只能怀疑移动运营商。jiji1就会网络不好的时候表现不好，可能jiji2继承了这一点。

最后换个DNS试试 例如223.5.5.5

**Comment by xiahuaijia** [comment]
```
time="2023-04-23 18:29:30" level=error msg="GetFromRestClient resp error: Get "[https://api.bilibili.com/x/web-interface/nav\](https://api.bilibili.com/x/web-interface/nav%5C)": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time="2023-04-23 18:29:30" level=error msg="RefreshLoginStatus json error: unexpected end of JSON input"
```
> 我怀疑我的core闪退的问题可能源自我家网络的问题。前两天拒绝移动的改套餐电话后网络一直加载巨慢，但下载速度没有问题。我目前还没排查出来是哪里的问题，只能怀疑移动运营商。jiji1就会网络不好的时候表现不好，可能jiji2继承了这一点。


1. 这个是你自己的网络问题和唧唧 1/2 没有任何关系, `Client.Timeout exceeded while awaiting headers` 翻译: 连接超时. 你连不上屑站的服务器
2. 还有如果是相同问题可以继续回复, 不同问题请另外打开一个
