### ISSUE TITLE
up主投稿视频下载错误

### ISSUE THREAD

**Issue by bixudamajiang** [JiJiDown/Tracker#9]
**描述错误**
无法使用up主uid下载投稿视频。

问题描述不正确或缺少信息会要求补充信息, 7 天内未补充会被关闭问题。

**软件信息**

 - 你使用的是什么系统: [例如: macOS / Linux / Windows]
 Microsoft Windows [版本 10.0.19045.2846]

 - 软件版本号: [例如: git.r224.efbbba9]
git.r281.230cfba0

 - (可选) 下载问题请添加视频地址: [例如:  ht<span>tps://</span>w<span>ww.</span>bilibili.com/video/av10086]
https://space.bilibili.com/23052222/video

**重现**
重现此行为的步骤:

1. 转到"首页"
2. 点击输入窗口
3. 输入 'up1'
4. 看到错误

**预期行为**

**附加日志**

```log
time="2023-04-21 20:36:07" level=info msg="Welcome to JiJiDownCore git.r281.230cfba0 windows/amd64 with go1.20.3"
time="2023-04-21 20:36:07" level=info msg="Built on 2023-04-19 19:48:56"
time="2023-04-21 20:36:07" level=info msg="Copyright 2014-2023 - JiJiDown.com"
time="2023-04-21 20:36:07" level=info msg="Configuration file location: C:\\Users\\12269\\AppData\\Roaming\\JiJiDown\\config.yaml"
time="2023-04-21 20:36:07" level=info msg="JiJiDownCore Start..."
time="2023-04-21 20:36:07" level=debug msg=RefreshLoginStatus
time="2023-04-21 20:36:07" level=fatal msg="External controller gRPC listen error: listen tcp 127.0.0.1:64000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

**Comment by xiahuaijia** [comment]
虽然日志和问题毫无关系, 但是确认了有这个问题

屑站应该在瞎jb改接口, 可以稍后重试一下

```
{"code":-509,"message":"请求过于频繁，请稍后再试","ttl":1}
```

**Comment by bixudanajiang** [comment]
我用过过一个人写的py脚本，当时也是看到同样的问题（抓下来的数据中包含这个字典），之后我做了修改，修改内容是在每次请求之间增加间隔(2s)，然后能运行（很勉强）。可能不是接口问题？

那个py脚本:
'''
https://github.com/Eathoublu/BilibiliUserDownloader
'''

**Comment by bixudamajiang** [comment]
我用过过一个人写的py脚本，当时也是看到同样的问题（抓下来的数据中包含这个字典），之后我做了修改，修改内容是在每次请求之间增加间隔(2s)，然后能运行（很勉强）。可能不是接口问题？

那个py脚本:
https://github.com/Eathoublu/BilibiliUserDownloader

**Comment by xiahuaijia** [comment]
> B站视频不行了
> pcdn被打，移动全面开战，大部分视频都切cdn了
> 现在视频就是弄虚作假，4k看着像1080p， 1080p视频看着像720p，720p的视频就是vcd画质

在别的地方看了, b站好像被打了

**Comment by xiahuaijia** [comment]
此问题一个月内没有任何更新, 问题关闭
